name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - ansible
  - ansible-kernel
  - ansible-runner
  - bash_kernel
  - imgaug
  - jupyter
  - jupyterhub
  - jupyterlab
  - jupyterlab-dash
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-transient-display-data
  - jupyterlab_heroku
  - jupyterlab_server
  - jupyterthemes
  - keras
  - opencv
  - pip
  - pycocotools
  - pygments
  - pyqt
  - scikit-image
  - tensorflow
  - tensorflow-gpu
  - pip:
      - gnuplot-kernel
      - google-auth
      - jupyter-c-kernel
      - markdown
      - matlab-kernel
      - metakernel
      - numpy
      - opt-einsum
      - plumbum
      - portalocker
      - powershell-kernel
      - protobuf
      - pyasn1-modules
      - pyqt5-sip
      - pyqtwebengine
      - setuptools
      - sshkernel
      - tensorboard
      - wurlitzer
      - zsh-jupyter-kernel
