channels:
  - defaults
  - conda-forge
dependencies:
  - grpcio-tools
  - h5py
  - imgaug
  - ipython[All]
  - jupyter
  - jupyterlab
  - keras
  - numpy
  - opencv
  - pip
  - pipenv
  - protobuf
  # - pycocotools # unsupported on Windows
  - pygments
  - pyqt
  - scikit-image
  - scipy
  - tensorflow
  - tensorflow-gpu
  - pip:
      - tensorflow-serving-api
